# Generated by Django 3.2.8 on 2021-11-10 02:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0002_auto_20211110_0235'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_num', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_status', models.CharField(max_length=100)),
                ('total_price', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.customer')),
            ],
        ),
    ]
