# Generated by Django 3.2.8 on 2021-11-10 02:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0003_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink_Menu',
            fields=[
                ('drink_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('drink_name', models.CharField(max_length=100)),
                ('d_price', models.IntegerField()),
            ],
        ),
    ]
