# Generated by Django 3.2.8 on 2021-11-10 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0004_drink_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_quantity', models.IntegerField()),
                ('drink_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.drink_menu')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.order')),
            ],
        ),
    ]
