# Generated by Django 3.2.8 on 2021-11-10 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0007_buns_menu_patty_menu_sauce_menu_veggie_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Burger_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_quantity', models.IntegerField()),
                ('buns', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.buns_menu')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.order')),
                ('patty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.patty_menu')),
                ('sauce', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.sauce_menu')),
                ('veggies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.veggie_menu')),
            ],
        ),
    ]
