# Generated by Django 3.2.8 on 2021-11-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0008_burger_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_num',
            field=models.CharField(max_length=10, verbose_name='Phone Number'),
        ),
    ]
