# Generated by Django 3.2.8 on 2021-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0009_auto_20211110_0426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(max_length=100, verbose_name='Order Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.IntegerField(verbose_name='Total Price'),
        ),
    ]
