# Generated by Django 3.2.8 on 2021-11-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0010_auto_20211110_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buns_menu',
            name='b_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='burger_order',
            name='b_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='drink_menu',
            name='d_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='drink_order',
            name='d_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='patty_menu',
            name='p_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='sauce_menu',
            name='s_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='side_menu',
            name='s_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='side_order',
            name='s_quantity',
            field=models.IntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='veggie_menu',
            name='veggie_price',
            field=models.IntegerField(verbose_name='Price'),
        ),
    ]
