# Generated by Django 3.2.8 on 2021-11-10 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0012_auto_20211110_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='burger_restaurant.customer'),
            preserve_default=False,
        ),
    ]
