# Generated by Django 3.2.8 on 2021-11-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0013_order_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buns_menu',
            name='buns_name',
            field=models.CharField(max_length=100, verbose_name='Buns Name'),
        ),
        migrations.AlterField(
            model_name='drink_menu',
            name='drink_name',
            field=models.CharField(max_length=100, verbose_name='Drink Name'),
        ),
        migrations.AlterField(
            model_name='patty_menu',
            name='patty_name',
            field=models.CharField(max_length=100, verbose_name='Patty Name'),
        ),
        migrations.AlterField(
            model_name='sauce_menu',
            name='sauce_name',
            field=models.CharField(max_length=100, verbose_name='Sauce Name'),
        ),
        migrations.AlterField(
            model_name='side_menu',
            name='side_name',
            field=models.CharField(max_length=100, verbose_name='Side Name'),
        ),
        migrations.AlterField(
            model_name='veggie_menu',
            name='veggie_name',
            field=models.CharField(max_length=100, verbose_name='Vegetable Name'),
        ),
    ]
