# Generated by Django 3.2.8 on 2021-11-15 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0014_auto_20211110_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
    ]
