# Generated by Django 3.2.8 on 2021-11-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burger_restaurant', '0015_alter_customer_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not Started', 'Not Started'), ('In Progress', 'In Progress'), ('Finished', 'Finished')], max_length=100, verbose_name='Order Status'),
        ),
    ]
